services:
  issdb:
    image: mysql:5.7.36
    environment:
      - MYSQL_DATABASE=iss-db
      - MYSQL_USER=jared
      - MYSQL_PASSWORD=jared
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./mysql_volume:/var/lib/mysql
